# Generated by Django 2.2.9 on 2020-01-15 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_question_prompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_prompt',
        ),
    ]
